Update install-duplicity
Changed dependencies to try and prevent future "Exception: cannot import name UnrewindableBodyError". This happened to me after a Centos 7 upgrade. The cause is a conflict between pip and yum packages. See https://ask.openstack.org/en/question/110437/importerror-cannot-import-name-unrewindablebodyerror/ for a fix.